# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: double-quote-string-fixer
    exclude: &exclude_files >
      (?x)^(
          .*.cif
      )$
  - id: end-of-file-fixer
    exclude: *exclude_files
  - id: fix-encoding-pragma
    exclude: *exclude_files
  - id: mixed-line-ending
    exclude: *exclude_files
  - id: trailing-whitespace
    exclude: *exclude_files

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: docker-clang-format
  - id: docker-cppcheck
  # enable below for linting
  # - id: cpplint
